// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: habitantes.proto

package misc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InicializadorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumHabitantes int32 `protobuf:"varint,1,opt,name=num_habitantes,json=numHabitantes,proto3" json:"num_habitantes,omitempty"`
}

func (x *InicializadorRequest) Reset() {
	*x = InicializadorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habitantes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InicializadorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicializadorRequest) ProtoMessage() {}

func (x *InicializadorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habitantes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicializadorRequest.ProtoReflect.Descriptor instead.
func (*InicializadorRequest) Descriptor() ([]byte, []int) {
	return file_habitantes_proto_rawDescGZIP(), []int{0}
}

func (x *InicializadorRequest) GetNumHabitantes() int32 {
	if x != nil {
		return x.NumHabitantes
	}
	return 0
}

type InicializadorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EstadosIniciales []int32 `protobuf:"varint,1,rep,packed,name=estados_iniciales,json=estadosIniciales,proto3" json:"estados_iniciales,omitempty"`
}

func (x *InicializadorResponse) Reset() {
	*x = InicializadorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habitantes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InicializadorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicializadorResponse) ProtoMessage() {}

func (x *InicializadorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habitantes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicializadorResponse.ProtoReflect.Descriptor instead.
func (*InicializadorResponse) Descriptor() ([]byte, []int) {
	return file_habitantes_proto_rawDescGZIP(), []int{1}
}

func (x *InicializadorResponse) GetEstadosIniciales() []int32 {
	if x != nil {
		return x.EstadosIniciales
	}
	return nil
}

type EstadoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request int32 `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *EstadoRequest) Reset() {
	*x = EstadoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habitantes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoRequest) ProtoMessage() {}

func (x *EstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habitantes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoRequest.ProtoReflect.Descriptor instead.
func (*EstadoRequest) Descriptor() ([]byte, []int) {
	return file_habitantes_proto_rawDescGZIP(), []int{2}
}

func (x *EstadoRequest) GetRequest() int32 {
	if x != nil {
		return x.Request
	}
	return 0
}

type EstadoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta []int32 `protobuf:"varint,1,rep,packed,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *EstadoResponse) Reset() {
	*x = EstadoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_habitantes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoResponse) ProtoMessage() {}

func (x *EstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habitantes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoResponse.ProtoReflect.Descriptor instead.
func (*EstadoResponse) Descriptor() ([]byte, []int) {
	return file_habitantes_proto_rawDescGZIP(), []int{3}
}

func (x *EstadoResponse) GetRespuesta() []int32 {
	if x != nil {
		return x.Respuesta
	}
	return nil
}

var File_habitantes_proto protoreflect.FileDescriptor

var file_habitantes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x22, 0x3d,
	0x0a, 0x14, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x5f, 0x68, 0x61,
	0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x6e, 0x75, 0x6d, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x22, 0x44, 0x0a,
	0x15, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x73, 0x5f, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x10, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x73, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61,
	0x6c, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e,
	0x0a, 0x0e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32, 0x95,
	0x02, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x48, 0x61, 0x62, 0x69, 0x74,
	0x61, 0x6e, 0x74, 0x65, 0x73, 0x12, 0x62, 0x0a, 0x17, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x48, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73,
	0x12, 0x20, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e, 0x49, 0x6e,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e,
	0x49, 0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x10, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x19, 0x2e,
	0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74,
	0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x69, 0x72, 0x52, 0x65, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x12, 0x19, 0x2e, 0x68, 0x61,
	0x62, 0x69, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74, 0x61, 0x6e,
	0x74, 0x65, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x6d, 0x69, 0x73, 0x63, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_habitantes_proto_rawDescOnce sync.Once
	file_habitantes_proto_rawDescData = file_habitantes_proto_rawDesc
)

func file_habitantes_proto_rawDescGZIP() []byte {
	file_habitantes_proto_rawDescOnce.Do(func() {
		file_habitantes_proto_rawDescData = protoimpl.X.CompressGZIP(file_habitantes_proto_rawDescData)
	})
	return file_habitantes_proto_rawDescData
}

var file_habitantes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_habitantes_proto_goTypes = []interface{}{
	(*InicializadorRequest)(nil),  // 0: habitantes.InicializadorRequest
	(*InicializadorResponse)(nil), // 1: habitantes.InicializadorResponse
	(*EstadoRequest)(nil),         // 2: habitantes.EstadoRequest
	(*EstadoResponse)(nil),        // 3: habitantes.EstadoResponse
}
var file_habitantes_proto_depIdxs = []int32{
	0, // 0: habitantes.ServicioHabitantes.InicializadorHabitantes:input_type -> habitantes.InicializadorRequest
	2, // 1: habitantes.ServicioHabitantes.ActualizarEstado:input_type -> habitantes.EstadoRequest
	2, // 2: habitantes.ServicioHabitantes.ConsumirRecurso:input_type -> habitantes.EstadoRequest
	1, // 3: habitantes.ServicioHabitantes.InicializadorHabitantes:output_type -> habitantes.InicializadorResponse
	3, // 4: habitantes.ServicioHabitantes.ActualizarEstado:output_type -> habitantes.EstadoResponse
	3, // 5: habitantes.ServicioHabitantes.ConsumirRecurso:output_type -> habitantes.EstadoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_habitantes_proto_init() }
func file_habitantes_proto_init() {
	if File_habitantes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_habitantes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InicializadorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_habitantes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InicializadorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_habitantes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_habitantes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_habitantes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_habitantes_proto_goTypes,
		DependencyIndexes: file_habitantes_proto_depIdxs,
		MessageInfos:      file_habitantes_proto_msgTypes,
	}.Build()
	File_habitantes_proto = out.File
	file_habitantes_proto_rawDesc = nil
	file_habitantes_proto_goTypes = nil
	file_habitantes_proto_depIdxs = nil
}
